-- Create syntax for TABLE 'ims_lonaking_new_gift_shop_ad'
CREATE TABLE `ims_lonaking_new_gift_shop_ad` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `title` varchar(255) DEFAULT '',
  `image` varchar(255) DEFAULT '',
  `url` varchar(255) DEFAULT '',
  `type` tinyint(2) DEFAULT '1',
  `create_time` int(11) DEFAULT NULL,
  `update_time` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyIsam AUTO_INCREMENT=15 DEFAULT CHARSET=utf8;

-- Create syntax for TABLE 'ims_lonaking_new_gift_shop_address'
CREATE TABLE `ims_lonaking_new_gift_shop_address` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `name` varchar(100) DEFAULT '',
  `mobile` varchar(11) DEFAULT '',
  `address` varchar(255) DEFAULT '',
  `province` varchar(20) DEFAULT '' COMMENT '省',
  `city` varchar(20) DEFAULT '' COMMENT '市',
  `area` varchar(20) DEFAULT '' COMMENT '区',
  `user_id` int(11) DEFAULT NULL,
  `openid` varchar(255) DEFAULT '',
  `remark` varchar(255) DEFAULT '',
  `create_time` int(11) DEFAULT NULL,
  `update_time` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyIsam AUTO_INCREMENT=61 DEFAULT CHARSET=utf8;

-- Create syntax for TABLE 'ims_lonaking_new_gift_shop_block'
CREATE TABLE `ims_lonaking_new_gift_shop_block` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `openid` varchar(255) DEFAULT '',
  `msgid` varchar(255) DEFAULT '',
  `createtime` varchar(255) DEFAULT '',
  `status` tinyint(1) DEFAULT '0' COMMENT '0正常 1锁表中',
  `create_time` int(11) DEFAULT NULL,
  `update_time` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- Create syntax for TABLE 'ims_lonaking_new_gift_shop_cash'
CREATE TABLE `ims_lonaking_new_gift_shop_cash` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `uid` int(11) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `openid` varchar(255) DEFAULT '',
  `amount` decimal(10,2) DEFAULT '0.00',
  `status` tinyint(1) DEFAULT '0' COMMENT '0 新的提现申请 1 已支付 2.拒绝',
  `remark` varchar(255) DEFAULT '' COMMENT '备注、拒绝理由',
  `option_time` int(11) DEFAULT NULL COMMENT '拒绝、审核时间',
  `create_time` int(11) DEFAULT NULL,
  `update_time` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyIsam DEFAULT CHARSET=utf8;

-- Create syntax for TABLE 'ims_lonaking_new_gift_shop_gift'
CREATE TABLE `ims_lonaking_new_gift_shop_gift` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `type` tinyint(1) DEFAULT '1' COMMENT '1微信红包 2 虚拟物品(券) 3实物礼品 4自领礼品 5话费 6. 流量 7. 积分抽积分',
  `group_id` int(11) DEFAULT NULL COMMENT '分组id',
  `view_type` int(2) DEFAULT '1' COMMENT '1 默认 2横排 3默认和横排',
  `auto` tinyint(1) DEFAULT '0' COMMENT '0 关闭 1自动审核',
  `num` int(11) DEFAULT '0' COMMENT '剩余库存',
  `buy_limit_day` int(11) DEFAULT '1' COMMENT '天数 指定多少天内每人可兑换多少个',
  `buy_limit_num` int(11) DEFAULT '0' COMMENT '每指定时间段最多可兑换多少次',
  `buy_limit_total` int(11) DEFAULT '0' COMMENT '每人可兑换的总数',
  `raffle` tinyint(1) DEFAULT '0' COMMENT '是否是抽奖:0普通模式 1指定抽奖模式 2随机抽奖模式',
  `raffle_min` int(11) DEFAULT '0' COMMENT '随机数最小',
  `raffle_max` int(11) DEFAULT '0' COMMENT '随机数最大',
  `raffle_hit` text,
  `raffle_chance` int(3) DEFAULT '0',
  `hide` tinyint(4) DEFAULT '0' COMMENT '是否隐藏 0不隐藏 1隐藏',
  `reduce_type` tinyint(1) DEFAULT '1' COMMENT '1 下单扣除 2付款扣除',
  `start_date` datetime DEFAULT NULL COMMENT '领取开始日期',
  `end_date` datetime DEFAULT NULL COMMENT '领取结束日期',
  `title` varchar(100) DEFAULT '',
  `tag` varchar(5) DEFAULT '' COMMENT '自定义角标',
  `tag_color` varchar(10) DEFAULT '' COMMENT '角标底色',
  `link_address` varchar(255) DEFAULT '' COMMENT '联系地址',
  `link_phone` varchar(30) DEFAULT '' COMMENT '联系电话',
  `undelivered_desc` varchar(255) DEFAULT '' COMMENT '待发货文案',
  `suspense_desc` varchar(255) DEFAULT '' COMMENT '兑换成功未处理文案',
  `buy_tip` varchar(50) DEFAULT '' COMMENT '兑换提示',
  `description` text,
  `guidelines` text COMMENT '使用说明 成功后的',
  `detail_image` varchar(1000) DEFAULT NULL COMMENT '商品图片',
  `thumbnail` varchar(255) DEFAULT '' COMMENT '缩略图',
  `icon` varchar(255) DEFAULT '' COMMENT '图标',
  `banner` varchar(255) DEFAULT '',
  `market_price` decimal(10,2) DEFAULT '0.00' COMMENT '市场价格',
  `buy_type` tinyint(1) DEFAULT '1' COMMENT '1 积分 2 余额 3积分+余额 ',
  `score` int(11) DEFAULT '0' COMMENT '需要积分',
  `money` decimal(10,2) DEFAULT '0.00' COMMENT '需要余额',
  `trans_fee_pay_way` int(1) DEFAULT '1' COMMENT '1 微信支付 2货到支付 3微信支付＋货到支付',
  `trans_fee` decimal(10,2) DEFAULT '0.00' COMMENT '邮费',
  `rank` int(11) DEFAULT '1' COMMENT '排序 越大越靠前',
  `hb_amount` decimal(10,2) DEFAULT '1.00' COMMENT '红包金额 单位元，默认为1',
  `hb_mode` tinyint(1) DEFAULT '1' COMMENT '红包模式 1固定金额 2随机金额',
  `hb_random_min` decimal(10,2) DEFAULT '1.00' COMMENT '随机红包金额最小数',
  `hb_random_max` decimal(10,2) DEFAULT '1.00' COMMENT '随机金额最大数',
  `hf_amount` decimal(10,2) DEFAULT '0.00' COMMENT '话费金额',
  `ll_amount` int(5) DEFAULT '0' COMMENT '流量金额',
  `raffle_score_amount` int(11) DEFAULT '0' COMMENT '抽奖奖励积分金额',
  `valid_date_type` tinyint(1) DEFAULT '1' COMMENT '1 核销日期 2几天后',
  `valid_date_after_days` int(10) DEFAULT '0' COMMENT '0为不限制',
  `validate_start_date` date DEFAULT NULL COMMENT '有效开始日期',
  `validate_end_date` date DEFAULT NULL COMMENT '有效结束日期',
  `success_redirect` varchar(255) DEFAULT '' COMMENT '跳转地址',
  `lat` decimal(10,6) DEFAULT '0.000000' COMMENT '地理纬度',
  `lng` decimal(10,6) DEFAULT '0.000000' COMMENT '地理经度',
  `radius` int(10) DEFAULT '-1' COMMENT '半径 千米',
  `abnormal_rank` tinyint(4) DEFAULT '0' COMMENT '反作弊规则级别 0 关闭 1 开启',
  `mc_group_limit` tinyint(1) DEFAULT '0' COMMENT '是否限制会员组 0不限制 1限制',
  `mc_group` varchar(255) DEFAULT '' COMMENT '会员组信息',
  `distribute_score` int(10) DEFAULT '0' COMMENT '分销奖励积分',
  `distribute_amount` decimal(10,2) DEFAULT '0.00' COMMENT '分销奖励现金',
  `share_score` int(11) DEFAULT '0',
  `share_amount` decimal(10,2) DEFAULT '0.00',
  `reward_score` int(11) DEFAULT '0' COMMENT '购买奖励积分',
  `reward_amount` decimal(10,2) DEFAULT '0.00',
  `status` tinyint(1) DEFAULT '1' COMMENT '-1停止 1在售',
  `money_to_score_flag` tinyint(1) DEFAULT '0',
  `money_to_score` int(11) DEFAULT '0',
  `create_time` int(11) DEFAULT NULL,
  `update_time` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyIsam AUTO_INCREMENT=17 DEFAULT CHARSET=utf8;

-- Create syntax for TABLE 'ims_lonaking_new_gift_shop_gift_image'
CREATE TABLE `ims_lonaking_new_gift_shop_gift_image` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `gift_id` int(11) DEFAULT NULL,
  `type` tinyint(1) DEFAULT '1' COMMENT '1微信红包 2 虚拟物品(券) 3实物礼品 4自领礼品 5话费 6. 流量 7. 积分抽积分',
  `raffle` tinyint(1) DEFAULT '0' COMMENT '是否是抽奖:0普通模式 1抽奖',
  `start_date` datetime DEFAULT NULL,
  `end_date` datetime DEFAULT NULL,
  `title` varchar(100) DEFAULT '',
  `tag` varchar(5) DEFAULT '' COMMENT '自定义角标',
  `tag_color` varchar(10) DEFAULT '' COMMENT '角标底色',
  `link_phone` varchar(30) DEFAULT '' COMMENT '联系电话',
  `link_address` varchar(255) DEFAULT '' COMMENT '联系地址',
  `undelivered_desc` varchar(255) DEFAULT '' COMMENT '待发货文案',
  `suspense_desc` varchar(255) DEFAULT '' COMMENT '兑换成功未处理文案',
  `description` text,
  `guidelines` text COMMENT '使用说明',
  `detail_image` varchar(255) DEFAULT '' COMMENT '详情图',
  `thumbnail` varchar(255) DEFAULT '' COMMENT '缩略图',
  `icon` varchar(255) DEFAULT '' COMMENT '图标',
  `banner` varchar(255) DEFAULT '',
  `market_price` decimal(10,2) DEFAULT '0.00' COMMENT '市场价格',
  `buy_type` tinyint(1) DEFAULT '1' COMMENT '1 积分 2 余额 3积分+余额 ',
  `score` int(11) DEFAULT '0' COMMENT '需要积分',
  `money` decimal(10,2) DEFAULT '0.00' COMMENT '需要余额',
  `trans_fee_pay_way` tinyint(1) DEFAULT '1' COMMENT '1 微信支付 2货到支付 3微信支付＋货到支付',
  `trans_fee` decimal(10,2) DEFAULT '0.00' COMMENT '邮费',
  `hb_amount` decimal(10,2) DEFAULT '1.00' COMMENT '红包金额 单位元，默认为1',
  `hb_mode` tinyint(1) DEFAULT '1' COMMENT '红包模式 1固定金额 2随机金额',
  `hb_random_min` decimal(10,2) DEFAULT '0.00' COMMENT '红包金额下限',
  `hb_random_max` decimal(10,2) DEFAULT '1.00' COMMENT '随机金额最大数',
  `hf_amount` decimal(10,2) DEFAULT '0.00',
  `ll_amount` int(10) DEFAULT '0',
  `raffle_score_amount` int(10) DEFAULT '0',
  `valid_date_type` tinyint(1) DEFAULT '1',
  `valid_date_after_days` int(10) DEFAULT '0',
  `validate_start_date` date DEFAULT NULL,
  `validate_end_date` date DEFAULT NULL,
  `success_redirect` varchar(255) DEFAULT '' COMMENT '跳转地址',
  `distribute_score` int(11) DEFAULT '0',
  `distribute_amount` decimal(10,2) DEFAULT '0.00',
  `share_score` int(11) DEFAULT '0',
  `share_amount` decimal(10,2) DEFAULT '0.00',
  `reward_score` int(11) DEFAULT '0',
  `reward_amount` decimal(10,2) DEFAULT '0.00',
  `abnormal_rank` tinyint(4) DEFAULT '0' COMMENT '反作弊规则级别 0 关闭 1 开启',
  `create_time` int(11) DEFAULT NULL,
  `update_time` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyIsam AUTO_INCREMENT=620 DEFAULT CHARSET=utf8;

-- Create syntax for TABLE 'ims_lonaking_new_gift_shop_gift_raffle'
CREATE TABLE `ims_lonaking_new_gift_shop_gift_raffle` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `gift_id` int(11) DEFAULT NULL,
  `time` int(11) DEFAULT '0',
  `create_time` int(11) DEFAULT NULL,
  `update_time` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyIsam AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

-- Create syntax for TABLE 'ims_lonaking_new_gift_shop_group'
CREATE TABLE `ims_lonaking_new_gift_shop_group` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `name` varchar(20) DEFAULT '',
  `icon` varchar(255) DEFAULT '',
  `create_time` int(11) DEFAULT NULL,
  `update_time` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyIsam AUTO_INCREMENT=14 DEFAULT CHARSET=utf8;

-- Create syntax for TABLE 'ims_lonaking_new_gift_shop_hb_config'
CREATE TABLE `ims_lonaking_new_gift_shop_hb_config` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `mode` tinyint(1) DEFAULT '0' COMMENT '0 非借权 1借权',
  `appid` varchar(255) DEFAULT '',
  `mchid` varchar(255) DEFAULT '',
  `passkey` varchar(255) DEFAULT '',
  `nick_name` varchar(10) DEFAULT '',
  `send_name` varchar(10) DEFAULT '',
  `wishing` varchar(20) DEFAULT '',
  `act_name` varchar(10) DEFAULT '',
  `remark` varchar(20) DEFAULT '',
  `client_ip` varchar(30) DEFAULT '127.0.0.1',
  `apiclient_cert` varchar(255) DEFAULT '',
  `apiclient_cert_content` text,
  `apiclient_key` varchar(255) DEFAULT '',
  `apiclient_key_content` text,
  `rootca` varchar(255) DEFAULT '',
  `rootca_content` text,
  `create_time` int(11) DEFAULT NULL,
  `update_time` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyIsam AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;

-- Create syntax for TABLE 'ims_lonaking_new_gift_shop_invite_record'
CREATE TABLE `ims_lonaking_new_gift_shop_invite_record` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `uid` int(11) DEFAULT NULL,
  `openid` varchar(255) DEFAULT '',
  `nickname` varchar(100) DEFAULT '',
  `invite_user_id` int(11) DEFAULT NULL,
  `invite_uid` int(11) DEFAULT NULL,
  `invite_openid` varchar(255) DEFAULT '',
  `invite_nickname` varchar(255) DEFAULT '',
  `score` int(11) DEFAULT '0',
  `money` decimal(10,2) DEFAULT '0.00',
  `status` tinyint(1) DEFAULT '1' COMMENT '1 关注 2取消关注',
  `create_time` int(11) DEFAULT NULL,
  `update_time` int(11) DEFAULT NULL,
  `level` int(1) DEFAULT NULL COMMENT '邀请级别，1：直接邀请，2：邀请人的邀请人（上上级）……',
  `score_result` int(1) DEFAULT '0' COMMENT '奖励发放结果，0 未成功 1 成功',
  `money_result` int(1) DEFAULT '0' COMMENT '奖励发放结果，0 未成功 1 成功',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=45 DEFAULT CHARSET=utf8;

-- Create syntax for TABLE 'ims_lonaking_new_gift_shop_max_scene'
CREATE TABLE `ims_lonaking_new_gift_shop_max_scene` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `max_scene_id` int(11) DEFAULT '0',
  `create_time` int(11) DEFAULT NULL,
  `update_time` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyIsam AUTO_INCREMENT=14 DEFAULT CHARSET=utf8;

-- Create syntax for TABLE 'ims_lonaking_new_gift_shop_menu'
CREATE TABLE `ims_lonaking_new_gift_shop_menu` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `type` tinyint(1) DEFAULT '1',
  `name` varchar(20) DEFAULT '',
  `icon` varchar(255) DEFAULT '',
  `url` varchar(255) DEFAULT '',
  `click` int(11) DEFAULT '0',
  `rank` int(11) DEFAULT '1',
  `create_time` int(11) DEFAULT NULL,
  `update_time` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=19 DEFAULT CHARSET=utf8;

-- Create syntax for TABLE 'ims_lonaking_new_gift_shop_notice_config'
CREATE TABLE `ims_lonaking_new_gift_shop_notice_config` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) NOT NULL,
  `type` tinyint(1) DEFAULT NULL COMMENT '1客服消息 2模板消息',
  `get_notice` varchar(255) DEFAULT '',
  `check_status_access_notice` varchar(255) DEFAULT '',
  `check_status_refuse_notice` varchar(255) DEFAULT '',
  `send_notice` varchar(255) DEFAULT '',
  `create_time` int(10) DEFAULT NULL,
  `update_time` int(10) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyIsam AUTO_INCREMENT=17 DEFAULT CHARSET=utf8;

-- Create syntax for TABLE 'ims_lonaking_new_gift_shop_order'
CREATE TABLE `ims_lonaking_new_gift_shop_order` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) NOT NULL,
  `type` tinyint(1) DEFAULT '1' COMMENT '1微信红包 2 虚拟物品(券) 3实物礼品 4自领礼品 5话费 6. 流量 7. 积分抽积分',
  `order_num` varchar(255) DEFAULT NULL COMMENT '订单编号',
  `user_id` int(11) DEFAULT NULL,
  `uid` int(11) DEFAULT NULL,
  `openid` varchar(128) NOT NULL,
  `nickname` varchar(20) DEFAULT '',
  `address_id` int(11) DEFAULT NULL COMMENT '收货地址id',
  `real_gift_id` int(11) DEFAULT NULL COMMENT '真实礼品id',
  `gift_id` int(11) NOT NULL COMMENT '兑换的礼品',
  `buy_type` tinyint(1) DEFAULT '1' COMMENT '1 积分支付 2现金支付 3积分+现金支付',
  `order_score` int(11) DEFAULT '0' COMMENT '支付积分',
  `order_money` decimal(10,2) DEFAULT '0.00' COMMENT '支付金额',
  `pay_status` tinyint(1) DEFAULT '0' COMMENT '0 未支付 1已支付',
  `raffle` tinyint(1) DEFAULT '0' COMMENT '0.默认正常模式 1抽奖模式',
  `raffle_status` tinyint(1) DEFAULT '0' COMMENT '是否中奖:0未中奖 1中奖',
  `hb_amount` decimal(10,2) DEFAULT '0.00' COMMENT '红包金额',
  `hb_openid` varchar(200) DEFAULT '' COMMENT '红包发放的openid',
  `hb_status` tinyint(1) DEFAULT '1' COMMENT '1 红包未发放 2红包已发放 -1 红包发放失败',
  `trans_company` varchar(20) DEFAULT '' COMMENT '快递公司',
  `trans_num` varchar(100) DEFAULT '' COMMENT '快递单号',
  `trans_status` tinyint(1) DEFAULT '0' COMMENT '发货状态 0未发货 1已发货 2已收货',
  `trans_fee` decimal(10,1) NOT NULL DEFAULT '0.0' COMMENT '配送费',
  `trans_fee_status` tinyint(1) DEFAULT '1' COMMENT '1 未支付 2已支付',
  `trans_confirm_time` int(11) DEFAULT NULL COMMENT '收货时间',
  `zl_status` tinyint(1) DEFAULT '1' COMMENT '1 未领取 2已领取',
  `zl_time` int(11) DEFAULT NULL COMMENT '领取时间',
  `hf_amount` int(11) DEFAULT '0' COMMENT '话费金额',
  `hf_status` tinyint(1) DEFAULT '1' COMMENT '1 话费未发放 2话费已发放 ',
  `ll_amount` int(11) DEFAULT '0' COMMENT '流量数量 比如500M',
  `ll_status` tinyint(1) DEFAULT '1' COMMENT '1 流量未充值 2流量已充值',
  `quan_id` int(11) DEFAULT NULL COMMENT '虚拟物品的id',
  `quan_status` tinyint(1) DEFAULT '1' COMMENT '1 券未发 2 券已领取 3券已使用',
  `raffle_score_amount` int(11) DEFAULT '0' COMMENT '抽奖奖励积分金额',
  `raffle_score_status` tinyint(1) DEFAULT NULL COMMENT '1未发放 2已发放',
  `distribute_score` int(11) DEFAULT '0',
  `distribute_amount` decimal(10,2) DEFAULT '0.00',
  `share_score` int(11) DEFAULT '0',
  `share_amount` decimal(10,2) DEFAULT '0.00',
  `reward_score` int(11) DEFAULT '0',
  `reward_amount` decimal(10,2) DEFAULT '0.00',
  `invite_user_id` int(11) DEFAULT NULL COMMENT '邀请用户',
  `status` int(2) NOT NULL DEFAULT '0' COMMENT '状态 0待审核 1已审核 -1已拒绝',
  `remark` varchar(255) DEFAULT '' COMMENT '备注，拒绝理由等',
  `abnormal` tinyint(1) DEFAULT '0' COMMENT '是否异常订单 1是 0不是',
  `create_time` int(11) DEFAULT NULL,
  `update_time` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyIsam AUTO_INCREMENT=792 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

-- Create syntax for TABLE 'ims_lonaking_new_gift_shop_poster'
CREATE TABLE `ims_lonaking_new_gift_shop_poster` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `title` varchar(255) DEFAULT '',
  `start` int(11) DEFAULT NULL,
  `end` int(11) DEFAULT NULL,
  `mode` tinyint(1) DEFAULT '1' COMMENT '1.积分海报 2.现金海报 3积分+现金海报',
  `deep` tinyint(1) DEFAULT '1' COMMENT '级别 1 2 3 分别为1级 2级 3级奖励',
  `follow_score` int(11) DEFAULT '0',
  `unfollow_score` int(11) DEFAULT '0',
  `follow_money` decimal(10,2) DEFAULT '0.00',
  `unfollow_money` decimal(10,2) DEFAULT '0.00',
  `second_follow_score` int(11) DEFAULT '0',
  `second_unfollow_score` int(11) DEFAULT '0',
  `second_follow_money` decimal(10,2) DEFAULT '0.00',
  `second_unfollow_money` decimal(10,2) DEFAULT '0.00',
  `third_follow_score` int(11) DEFAULT '0',
  `third_unfollow_score` int(11) DEFAULT '0',
  `third_follow_money` decimal(10,2) DEFAULT '0.00',
  `third_unfollow_money` decimal(10,2) DEFAULT '0.00',
  `score_limit` int(11) DEFAULT '0',
  `money_limit` decimal(10,2) DEFAULT '0.00',
  `every_score_limit` int(11) DEFAULT '0',
  `poster_type` tinyint(1) DEFAULT '1' COMMENT '海报类型 1服务号 2订阅号',
  `follow_redirect` varchar(255) DEFAULT '',
  `poster_bg` varchar(255) DEFAULT '' COMMENT '背景',
  `poster_bg_r` varchar(255) DEFAULT '',
  `poster_name_position_x` int(11) DEFAULT '0',
  `poster_name_position_y` int(11) DEFAULT '0',
  `poster_name_color` varchar(10) DEFAULT '',
  `poster_name_font` varchar(100) DEFAULT '',
  `poster_name_font_size` int(5) DEFAULT '20',
  `poster_qrcode_position_x` int(11) DEFAULT '0',
  `poster_qrcode_position_y` int(11) DEFAULT '0',
  `poster_qrcode_side` int(4) DEFAULT '120',
  `poster_invite_code_position_x` int(11) DEFAULT '0',
  `poster_invite_code_position_y` int(11) DEFAULT '0',
  `poster_invite_code_color` varchar(10) DEFAULT '',
  `poster_invite_code_font` varchar(100) DEFAULT '',
  `poster_invite_code_font_size` int(5) DEFAULT '20',
  `poster_avatar_position_x` int(11) DEFAULT '0',
  `poster_avatar_position_y` int(11) DEFAULT '0',
  `poster_avatar_side` int(4) DEFAULT '80',
  `poster_has_avatar` tinyint(1) DEFAULT '1' COMMENT '是否包含头像',
  `poster_has_nickname` tinyint(1) DEFAULT '1' COMMENT '是否包含昵称',
  `subscribe_rewards_score` int(11) DEFAULT '0' COMMENT '关注奖励积分',
  `subscribe_tip` varchar(255) DEFAULT '' COMMENT '关注提示',
  `invitor_subscribe_tip` varchar(255) DEFAULT '',
  `second_invitor_subscribe_tip` varchar(255) DEFAULT '',
  `third_intivtor_subscribe_tip` varchar(255) DEFAULT '',
  `invitor_unsubscribe_tip` varchar(255) DEFAULT '',
  `second_invitor_unsubscribe_tip` varchar(255) DEFAULT '',
  `third_invitor_unsubscribe_tip` varchar(255) DEFAULT '',
  `create_time` int(11) DEFAULT NULL,
  `update_time` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyIsam AUTO_INCREMENT=21 DEFAULT CHARSET=utf8;

-- Create syntax for TABLE 'ims_lonaking_new_gift_shop_poster_record'
CREATE TABLE `ims_lonaking_new_gift_shop_poster_record` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `openid` varchar(200) DEFAULT '',
  `user_id` int(11) DEFAULT NULL,
  `msgid` varchar(255) DEFAULT '',
  `msg_times` int(1) DEFAULT '0',
  `in_posting` tinyint(1) DEFAULT '0' COMMENT '0 否 1是',
  `poster_times` int(11) DEFAULT '0',
  `poster_update_time` int(11) DEFAULT NULL,
  `create_time` int(10) DEFAULT NULL,
  `update_time` int(10) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

-- Create syntax for TABLE 'ims_lonaking_new_gift_shop_quan'
CREATE TABLE `ims_lonaking_new_gift_shop_quan` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `type` tinyint(1) DEFAULT '1' COMMENT '1 一券多用 2 一券一用',
  `gift_id` int(11) DEFAULT NULL,
  `hao` varchar(255) DEFAULT '' COMMENT '号码',
  `value` varchar(255) DEFAULT '' COMMENT '卡密',
  `status` tinyint(1) DEFAULT '0' COMMENT '1.未兑换 2.已兑换 3.已使用',
  `time` int(11) DEFAULT '1',
  `times` int(11) DEFAULT '0' COMMENT '兑换次数',
  `uid` int(11) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `openid` varchar(255) DEFAULT '',
  `get_time` int(11) DEFAULT NULL,
  `create_time` int(11) DEFAULT NULL,
  `update_time` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyIsam AUTO_INCREMENT=1126 DEFAULT CHARSET=utf8;

-- Create syntax for TABLE 'ims_lonaking_new_gift_shop_user'
CREATE TABLE `ims_lonaking_new_gift_shop_user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) NOT NULL,
  `mobile` varchar(11) DEFAULT '',
  `invite_code` varchar(11) DEFAULT '',
  `poster_times` int(11) DEFAULT '0',
  `in_posting` tinyint(1) DEFAULT '0' COMMENT '0 否 1是',
  `msg_id` varchar(100) DEFAULT '',
  `subscribe_charge_status` tinyint(1) DEFAULT '0' COMMENT '关注奖励 0未奖励 1已奖励',
  `uid` int(11) DEFAULT NULL,
  `subscribe` tinyint(1) DEFAULT '1' COMMENT '0未关注 1关注',
  `openid` varchar(255) DEFAULT '' COMMENT 'openid',
  `borrow_openid` varchar(255) DEFAULT '' COMMENT '借权发红包的权',
  `nickname` varchar(10) DEFAULT NULL COMMENT '姓名',
  `avatar` varchar(255) DEFAULT '' COMMENT '头像',
  `pid` int(11) DEFAULT '0' COMMENT '邀请人id',
  `poster` varchar(255) DEFAULT '' COMMENT '海报url',
  `poster_update_time` int(10) DEFAULT NULL,
  `qrcode` varchar(255) DEFAULT NULL,
  `qrcode_update_time` int(11) NOT NULL,
  `invite_score` int(11) NOT NULL DEFAULT '0' COMMENT '赚取积分',
  `invite_money` decimal(10,2) DEFAULT '0.00' COMMENT '赚取余额',
  `invite_count` int(11) NOT NULL DEFAULT '0' COMMENT '邀请人数',
  `invite_cancel_count` int(11) NOT NULL DEFAULT '0' COMMENT '邀请取消关注人数',
  `invite_cancel_score` int(11) DEFAULT '0' COMMENT '取消关注扣除积分',
  `invite_cancel_money` decimal(10,2) DEFAULT '0.00' COMMENT '取消关注扣除现金奖励',
  `second_invite_score` int(11) DEFAULT '0' COMMENT '二级邀请奖励积分',
  `second_invite_money` decimal(10,2) DEFAULT '0.00' COMMENT '二级邀请奖励现金金额',
  `second_invite_count` int(11) DEFAULT '0' COMMENT '二级邀请总数',
  `second_invite_cancel_count` int(11) DEFAULT '0' COMMENT '二级邀请取消数量',
  `second_invite_cancel_score` int(11) DEFAULT '0' COMMENT '二级取消扣除积分总数',
  `second_invite_cancel_money` decimal(10,2) DEFAULT '0.00' COMMENT '二级取消扣除余额总数',
  `third_invite_score` int(11) DEFAULT '0' COMMENT '三级邀请奖励积分',
  `third_invite_money` decimal(10,2) DEFAULT '0.00' COMMENT '三级邀请奖励现金金额',
  `third_invite_count` int(11) DEFAULT '0' COMMENT '三级邀请总数',
  `third_invite_cancel_count` int(11) DEFAULT '0' COMMENT '三级邀请取消总数',
  `third_invite_cancel_score` int(11) DEFAULT '0' COMMENT '三级取消扣除积分',
  `third_invite_cancel_money` decimal(10,2) DEFAULT '0.00' COMMENT '三级取消扣除现金总数',
  `total_invite_score` int(11) DEFAULT '0' COMMENT '邀请总积分',
  `total_invite_money` decimal(10,2) DEFAULT '0.00' COMMENT '邀请总金额',
  `block` tinyint(1) DEFAULT '0' COMMENT '0 正常 1锁表',
  `black` tinyint(1) DEFAULT '0' COMMENT '黑名单 1是 0否',
  `create_time` int(10) DEFAULT NULL,
  `update_time` int(10) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyIsam AUTO_INCREMENT=7135 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

CREATE TABLE `ims_lonaking_flash_cache` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `do_option` varchar(100) DEFAULT NULL,
  `do_res` text,
  `create_time` int(11) DEFAULT NULL,
  `update_time` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

CREATE TABLE `ims_lonaking_location_cache` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `openid` varchar(255) DEFAULT '',
  `w_lng` decimal(10,6) DEFAULT '0.000000',
  `w_lat` decimal(10,6) DEFAULT '0.000000',
  `b_lng` decimal(10,6) DEFAULT '0.000000',
  `b_lat` decimal(10,6) DEFAULT '0.000000',
  `d` decimal(10,2) DEFAULT '0.00',
  `create_time` int(11) DEFAULT NULL,
  `update_time` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `ims_lonaking_hb_record` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(11) DEFAULT NULL,
  `to_openid` varchar(255) DEFAULT '',
  `status` tinyint(1) DEFAULT '0' COMMENT '0 失败 1成功',
  `mch_billno` varchar(100) DEFAULT '',
  `send_data` text COMMENT '发送的数据json',
  `error_code` varchar(100) DEFAULT '',
  `response_obj_text` text COMMENT '微信回复内容',
  `response_return_code` varchar(200) DEFAULT '',
  `response_result_code` varchar(200) DEFAULT '',
  `response_return_msg` varchar(200) DEFAULT '',
  `response_err_code` varchar(200) DEFAULT '',
  `response_err_code_des` varchar(255) DEFAULT '',
  `amount` int(11) DEFAULT '0' COMMENT '发送金额',
  `create_time` int(11) DEFAULT NULL,
  `update_time` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=41 DEFAULT CHARSET=utf8;