<?php
//diy组件原型文件
	return [
		[ 
			"group"=>"1",//pc端分类
			"id"=>-1,
			"name"=>"导航栏", 
			"pid"=>0,
			"direction"=>"y",//拖动方式x,y,a
			"position"=>"", //布局方式，相对还是绝对，默认无
			"itemClass"=>"navbar",//小程序端会附加的类，子类自动附加class-item
			"rowsize"=>5,//每行显示多少个
			"rowsize_option"=>[
				"4"=>4,"5"=>5
			],//可选值
			"width"=>0,//宽度百分比，0未设置，0到10为百分比，大于10为像素
			"height"=>0,//高度百分比，0未设置，0到10为百分比，大于10为像素 
			"child_min"=>0,//子类最少多少个，不满足条件不能保存,0表示不限制
		 	"child_max"=>10,//子类最多多少个,不满足条件不能保存，0表示不限制
		 	"picture"=>"",
		 	"picture_size"=>1,//图片长宽比例
		 	"picture_size_option"=>[],
		 	
			"form_support"=>["rowsize","addchild"],
			"form_support_children"=>["picture","datatype"],
			"dataurl"=>"",
			"datatype"=>"",
			"tips"=>"导航栏最少3个图标，最多5个图标",//使用说明
			"children"=>[

			],
			"children_default_length"=>4
		],
		[
			"group"=>"1",
			"id"=>-1,
			"name"=>"轮播广告",   
			"pid"=>0,
			"direction"=>"y", 
			"position"=>"", 
			"itemClass"=>"carousel-x", 
			"picture"=>"",
		 	"picture_size"=>0.5,//图片长宽比例
		 	"picture_size_option"=>[
		 		"1:1"=>1,"2:1"=>0.5,"3:1"=>0.33,"4:1"=>0.25,"3:2"=>0.66,"4:3"=>0.75,"1:2"=>2,"2:3"=>1.5,"1:3"=>3
		 	],
		 	"child_min"=>0, 
		 	"child_max"=>10, 
		 	"form_support"=>["picturesize","addchild"],
		 	"form_support_children"=>["picture","datatype"],
			"children"=>[ 
			],
			"children_default_length"=>1
		],
	 	[
			"group"=>"1",
			"id"=>-1,
			"name"=>"订单轮播",  
			"pid"=>0,
			"direction"=>"y", 
			"position"=>"", 
			"itemClass"=>"carousel-order",  
		 	"child_min"=>0, 
		 	"child_max"=>1, 
		 	"form_support"=>[],
		 	"form_support_children"=>[], 
			"children"=>[],
			"tips"=>"随机查30个商品进行下单轮播。"//使用说明
		],
		[
			"group"=>"2",
			"id"=>-1,
			"name"=>"商品分类",
			"pid"=>0,
			"direction"=>"y", 
			"position"=>"", 
			"itemClass"=>"goods-cate", 
			"picture"=>"",
		 	"picture_size"=>1,//图片长宽比例
		 	"child_min"=>0, 
		 	"child_max"=>0, 
		 	"rowsize"=>2,
		 	"rowsize_option"=>[1,2,3],
		 	"datatype"=>"goodscate",
			"children"=>[ 

			],  
			"form_support"=>["rowsize","picturesize","cate","showtitle"],
			"picture_size_option"=>[
		 		"1:1"=>1,"3:2"=>0.66,"2:3"=>1.5
		 	], 
			"tips"=>"展示某个分类的前30个商品"//使用说明
		],
		[
			"group"=>"2",
			"id"=>-1,
			"name"=>"商品推荐(自定义)",
			"pid"=>0,
			"direction"=>"y", 
			"position"=>"", 
			"itemClass"=>"goods-list", 
			"datatype"=>"goods-list",
			"picture"=>"",
		 	"picture_size"=>1,//图片长宽比例
		 	"child_min"=>0, 
		 	"child_max"=>0, 
		 	"rowsize"=>2,
		 	"rowsize_option"=>[1,2,3],
			"children"=>[ 

			],  
			"picture_size_option"=>[
		 		"1:1"=>1,"3:2"=>0.66,"2:3"=>1.5
		 	], 
			"form_support"=>["rowsize","picturesize"], 
			"tips"=>"通过商品列表添加首页推荐，仅主管理员可操作"//使用说明
		],
		[
			"group"=>"3",
			"id"=>-1,
			"name"=>"3格广告位",
			"pid"=>0,
			"direction"=>"y", 
			"position"=>"", 
			"itemClass"=>"advert3", 
			"picture"=>"",
		 	"picture_size"=>0.5,//图片长宽比例
		 	"child_min"=>0, 
		 	"child_max"=>3, 
		 	"rowsize"=>0,
		 	"rowsize_option"=>[],
			"children"=>[ 
			], 
			"form_support"=>["addchild"],
			"form_support_children"=>['picture','datatype'],
			"datatype"=>"", 
			"children_default_length"=>3,
			"tips"=>"推荐像素比例：第一张为300*300像素，第二张、第三张为300*150像素"//使用说明
		], 
		[ 
			"group"=>"5",
			"id"=>-1,
			"name"=>"图片广告位",
			"pid"=>0,
			"direction"=>"y", 
			"position"=>"", 
			"itemClass"=>"advert-pics",  
			"content"=>"",
			"picture"=>"",
			"children"=>[ 
			],  
			"rowsize_option"=>[1,2,3,4,5],
			"picture_size_option"=>[
		 		"1:1"=>1,"2:1"=>0.5,"3:1"=>0.33,"4:1"=>0.25,"3:2"=>0.66,"4:3"=>0.75,"1:2"=>2,"2:3"=>1.5,"1:3"=>3
		 	],
		 	"children_default_length"=>1,
			"form_support"=>["addchild","rowsize","picturesize"],
			"form_support_children"=>["picture","datatype"],
			"datatype"=>"", 
			"tips"=>""//使用说明
		] , 
		[
			"group"=>"1",
			"id"=>-1,
			"name"=>"文字公告",  
			"pid"=>0,
			"direction"=>"y", 
			"position"=>"", 
			"itemClass"=>"carousel-notice",  
		 	"child_min"=>0, 
		 	"child_max"=>10, 
		 	"form_support"=>["addchild"],
		 	"form_support_children"=>["content"], 
			"children"=>[ 
			],
		],
		[
			"group"=>"4",
			"id"=>-1,
			"name"=>"悬浮按钮",
			"direction"=>"a",//拖动方式x,y,a
			"position"=>"fixed", //布局方式，相对还是绝对
			"itemClass"=>"fixedbtn",//附加的类,子类自动附加class-item
			"style"=>"",//小程序端会附加的样式 
			"picture"=>"",
			"form_support"=>["picture","datatype"],
			"children"=>[ 
			]
		], 
		 
		[//首页商品分页
			"group"=>"5",
			"id"=>-1,
			"name"=>"搜索",
			"pid"=>0,
			"direction"=>"y", 
			"position"=>"", 
			"itemClass"=>"search",  
			"children"=>[ 
			], 
			"datatype"=>"", 
			"tips"=>""//使用说明
		],
		
		[
			"group"=>"1",
			"id"=>-1,
			"name"=>"流量主",  
			"pid"=>0,
			"direction"=>"y", 
			"position"=>"", 
			"itemClass"=>"advert-wx", 
			"picture"=>"",
		 	"picture_size"=>0.5,//图片长宽比例
		 	"picture_size_option"=>[ 
		 	],
		 	"child_min"=>0, 
		 	"child_max"=>10, 
		 	"form_support"=>["advertid"],
		 	"form_support_children"=>[],
			"children"=>[ 
			],
			"tips"=>"小程序官方广告组件"//使用说明
		],
		[//首页商品分页
			"group"=>"5",
			"id"=>-1,
			"name"=>"优惠券",
			"pid"=>0,
			"direction"=>"y", 
			"position"=>"", 
			"itemClass"=>"coupon-list",  
			"children"=>[ 
			], 
			"form_support"=>["showtitle"],
			"datatype"=>"", 
			"tips"=>""//使用说明
		],
		[ 
			"group"=>"5",
			"id"=>-1,
			"name"=>"标题栏",
			"pid"=>0,
			"direction"=>"y", 
			"position"=>"", 
			"itemClass"=>"title",  
			"content"=>"",
			"picture"=>"",
			"children"=>[ 
			], 
			"form_support"=>["picture"],
			"datatype"=>"", 
			"tips"=>"有图片的情况下显示图片，没图片时显示文字，图片比例为600:40"//使用说明
		],
		[
			"group"=>"3",
			"id"=>-1,
			"name"=>"一元抢购",
			"pid"=>0,
			"direction"=>"y", 
			"position"=>"", 
			"itemClass"=>"goods-onemoney", 
			"datatype"=>"goods-onemoney",
			"picture"=>"",
		 	"picture_size"=>1,//图片长宽比例
		 	"child_min"=>0, 
		 	"child_max"=>3, 
		 	"rowsize"=>3,
		 	"rowsize_option"=>[1,2,3],
			"children"=>[ 
			],  
			"picture_size_option"=>[
		 		"1:1"=>1,"1:1"=>1,"1:1"=>1
		 	], 
			"form_support"=>["rowsize","picturesize","rowsizeall","snapup"], 
			"tips"=>"推荐像素比例：300*300像素"//使用说明
		],

	];